Repository CareSheep/CareSheep_Android, pull requests merged in 2023-09, with the labels that each got.

#99 design : 보호자 화면에서 어르신 음성 녹음 관련 UI 작업
  app/src/main/java/com/swu/caresheep/recyclerview/RecordAdapter.kt
  app/src/main/java/com/swu/caresheep/ui/guardian/GuardianVoiceDetailActivity.kt
  app/src/main/res/drawable/image_daily.png
  app/src/main/res/drawable/situation_type_daily.png
  app/src/main/res/layout/activity_elder_voice_sub.xml
  app/src/main/res/layout/activity_guardian_voice_detail.xml
  app/src/main/res/layout/layout_recycler_record_item.xml
  app/src/main/res/values/colors.xml
Labels: design

#100 fix : fcm 푸시 알림 intent 플래그 변경
  app/src/main/java/com/swu/caresheep/MyFirebaseMessagingService.kt
Labels: fix

#102 refactor, style, design: voice테이블 id 제거, gpt api 주석 제거, 상황에 따른 이미지
  app/src/main/java/com/swu/caresheep/Voice.kt
  app/src/main/java/com/swu/caresheep/elder/ElderVoiceSubActivity.kt
  app/src/main/java/com/swu/caresheep/ui/guardian/GuardianVoiceDetailActivity.kt
  app/src/main/res/drawable/image_need.png
  app/src/main/res/drawable/situation_type_emergency.png
  app/src/main/res/drawable/situation_type_need.png
  app/src/main/res/values/colors.xml
Labels: refactor, design

#103 design, refactor : ui 수정, voice_id 제거
  app/src/main/java/com/swu/caresheep/recyclerview/RecordAdapter.kt
  app/src/main/java/com/swu/caresheep/ui/guardian/GuardianVoiceDetailActivity.kt
  app/src/main/res/layout/activity_guardian_voice_detail.xml
Labels: refactor, design

#105 refactor : 불필요한 파일과 코드 삭제, 주석 변경(voice 기능 관련)
  app/src/main/java/com/swu/caresheep/NotificationType.kt
  app/src/main/java/com/swu/caresheep/elder/ElderVoiceMainActivity.kt
  app/src/main/java/com/swu/caresheep/elder/ElderVoiceSubActivity.kt
  app/src/main/java/com/swu/caresheep/recyclerview/RecordAdapter.kt
  app/src/main/java/com/swu/caresheep/recyclerview/RecycleMainRecordActivity.kt
  app/src/main/java/com/swu/caresheep/ui/guardian/GuardianVoiceDetailActivity.kt
  app/src/main/java/com/swu/caresheep/ui/start/UserAgeFragment.kt
  app/src/main/res/drawable/baseline_notifications_active_24.xml
  app/src/main/res/layout/view_custom_notification.xml
Labels: refactor

#106 design: 녹음 상세 내용 UI 수정
  app/src/main/java/com/swu/caresheep/ui/guardian/GuardianVoiceDetailActivity.kt
  app/src/main/res/drawable/ic_situation_type_daily.xml
  app/src/main/res/drawable/ic_situation_type_emergency.xml
  app/src/main/res/drawable/ic_situation_type_need.xml
  app/src/main/res/drawable/image_daily.png
  app/src/main/res/drawable/image_emergency.png
  app/src/main/res/drawable/image_need.png
  app/src/main/res/drawable/img_daily_illust.png
  app/src/main/res/drawable/img_emergency_illust.png
  app/src/main/res/drawable/img_need_illust.png
  app/src/main/res/drawable/situation_type_daily.png
  app/src/main/res/drawable/situation_type_emergency.png
  app/src/main/res/drawable/situation_type_need.png
  app/src/main/res/layout/activity_guardian_elder_routine.xml
  app/src/main/res/layout/activity_guardian_voice_detail.xml
  app/src/main/res/values/strings.xml
Labels: design

#107 fix: 로그인 및 회원가입 관련 Dialog 미표시 버그 수정
  app/src/main/java/com/swu/caresheep/MyFirebaseMessagingService.kt
  app/src/main/java/com/swu/caresheep/ui/start/SignUpActivity.kt
  app/src/main/java/com/swu/caresheep/ui/start/StartActivity.kt
Labels: fix

#108 refactor : 재알람 관련 동작 모듈화
  app/src/main/java/com/swu/caresheep/AlarmHandler.kt
  app/src/main/java/com/swu/caresheep/elder/ElderMedicineFirstActivity.kt
Labels: refactor

#111 fix: 회원가입 완료 시, 이전 액티비티를 모두 종료하게 수정
  app/src/main/java/com/swu/caresheep/ui/start/UserAgeFragment.kt
Labels: fix

#112 fix: 연동된 어르신의 루틴 미설정 시, 루틴 설정 화면으로 이동하지 않는 버그 수정
  app/src/main/java/com/swu/caresheep/ui/guardian/home/GuardianHomeFragment.kt
Labels: fix
