Repository CareSheep/CareSheep_Android, pull requests merged in 2023-11, with the labels that each got.

#116 design: 주간 생활 리포트 - 식사 루틴 추천 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/swu/caresheep/data/api/Gpt3Api.kt
  app/src/main/java/com/swu/caresheep/elder/voice/ElderVoiceSubActivity.kt
  app/src/main/java/com/swu/caresheep/guardian/mypage/GuardianConnectActivity.kt
  app/src/main/java/com/swu/caresheep/guardian/mypage/GuardianMyPageFragment.kt
  app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderMealRecommendActivity.kt
  app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderWeekReportDetailActivity.kt
  app/src/main/java/com/swu/caresheep/start/SignUpActivity.kt
  app/src/main/java/com/swu/caresheep/start/UserAgeFragment.kt
  app/src/main/java/com/swu/caresheep/utils/dialog/BaseDialog.kt
  app/src/main/java/com/swu/caresheep/utils/dialog/InputDialog.kt
  app/src/main/java/com/swu/caresheep/utils/dialog/VerticalDialog.kt
  app/src/main/res/drawable/circle_report_routine_check.xml
  app/src/main/res/drawable/dialog_base_btn.xml
  app/src/main/res/drawable/dialog_bottom_btn.xml
  app/src/main/res/drawable/dialog_btn.xml
  app/src/main/res/drawable/dialog_top_btn.xml
  app/src/main/res/drawable/ic_circle_thumb_up.xml
  app/src/main/res/drawable/ic_report_meal.xml
  app/src/main/res/layout/activity_guardian_elder_meal_recommend.xml
  app/src/main/res/layout/activity_guardian_elder_week_report_detail.xml
  app/src/main/res/layout/dialog_base.xml
  app/src/main/res/layout/dialog_input.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: design

#117 feat: 주간 리포트 상세 내역 구현
  app/src/main/java/com/swu/caresheep/guardian/home/GuardianHomeFragment.kt
  app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderMealRecommendActivity.kt
  app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderReportActivity.kt
  app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderWeekReportDetailActivity.kt
  app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderWeekReportFragment.kt
  app/src/main/java/com/swu/caresheep/utils/dialog/InputDialog.kt
  app/src/main/res/drawable/circle_report_routine_check.xml
  app/src/main/res/drawable/ic_circle_thumb_up_blue.xml
  app/src/main/res/drawable/ic_circle_thumb_up_yellow.xml
  app/src/main/res/drawable/ic_report_exercise.xml
  app/src/main/res/layout/activity_guardian_elder_week_report_detail.xml
  app/src/main/res/layout/fragment_guardian_elder_week_report.xml
  app/src/main/res/values/strings.xml
Labels: feature

#118 feat, design : 복약 설정 매뉴얼
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/swu/caresheep/guardian/emergency/GuardianSetEmergencyTimeActivity.kt
  app/src/main/java/com/swu/caresheep/guardian/routine/medicine/MedicineSettingManualActivity.kt
  app/src/main/res/drawable/medicine_manual.png
  app/src/main/res/layout/activity_medicine_setting_manual.xml
Labels: feature, design

#119 feat : kakao image search api로 이미지 불러오기
  app/build.gradle
  app/src/main/java/com/swu/caresheep/data/api/KakaoImgSearchApi.kt
  app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderMealRecommendActivity.kt
Labels: feature

#122 feat: 루틴 일간 및 주간 UI 및 구조 수정2
  app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderWeekReport2Fragment.kt
  app/src/main/res/layout/fragment_guardian_elder_week_report2.xml
Labels: feature

#123 fix : kakao api 를 이용해서 추천 식단에 대한 이미지 뜨도록
  app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderMealRecommendActivity.kt
Labels: fix

#124 fix: 식단 추천 로딩 텍스트 수정
  app/src/main/res/layout/activity_guardian_elder_meal_recommend.xml
Labels: fix

#125 fix: 식단 추천 레시피 누락 수정
  app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderMealRecommendActivity.kt
Labels: fix

#126 fix: 주간, 일간 리포트 UI 추가 수정 및 연결
  app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderWeekReport2Fragment.kt
  app/src/main/java/com/swu/caresheep/guardian/report/GuardianEldereReportViewAdapter.kt
  app/src/main/res/drawable/circle_progressbar_1.xml
  app/src/main/res/drawable/circle_progressbar_2.xml
  app/src/main/res/drawable/circle_progressbar_3.xml
  app/src/main/res/drawable/circle_progressbar_4.xml
  app/src/main/res/layout/activity_guardian_elder_report.xml
  app/src/main/res/layout/fragment_guardian_elder_today_report.xml
  app/src/main/res/layout/fragment_guardian_elder_week_report2.xml
  app/src/main/res/values/styles.xml
Labels: fix

#127 fix: 주간 리포트 상세내역 운동 루틴 수행률 업데이트 버그 수정
  app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderWeekReport2Fragment.kt
  app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderWeekReportDetailActivity.kt
  app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderWeekReportFragment.kt
Labels: fix

#130 fix: UI 계산 해결
  app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderWeekReport2Fragment.kt
  app/src/main/res/layout/fragment_guardian_elder_week_report2.xml
Labels: fix

#131 fix: 노인 걷는 시간 DB 추가 및 레포트 작업 수정
  app/src/main/java/com/swu/caresheep/elder/walk/ElderWalkActivity.kt
  app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderTodayReportFragment.kt
  app/src/main/res/layout/fragment_guardian_elder_today_report.xml
Labels: fix
