Repository CareSheep/CareSheep_Android, pull requests merged in 2023-08, with the labels that each got.

#74 test : 어르신 위치 지속 갱신 test
  app/src/main/java/com/swu/caresheep/ElderMapsActivity.kt
Labels: test

#75 공유 캘린더 중복 함수 utill화
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/swu/caresheep/data/model/GuardianSchedule.kt
  app/src/main/java/com/swu/caresheep/ui/elder/main/ElderActivity.kt
  app/src/main/java/com/swu/caresheep/ui/guardian/calendar/GuardianAddScheduleActivity.kt
  app/src/main/java/com/swu/caresheep/ui/guardian/calendar/GuardianCalendarFragment.kt
  app/src/main/java/com/swu/caresheep/ui/guardian/calendar/GuardianScheduleDetailActivity.kt
  app/src/main/java/com/swu/caresheep/ui/guardian/calendar/GuardianScheduleRVAdapter.kt
  app/src/main/java/com/swu/caresheep/ui/guardian/home/GuardianHomeFragment.kt
  app/src/main/java/com/swu/caresheep/ui/guardian/home/GuardianTodayScheduleRVAdapter.kt
  app/src/main/java/com/swu/caresheep/utils/CalendarUtil.kt
Labels: refactor

#80 refactor: 어르신 일정 조회 함수를 CalendarUtil로 대체
  app/src/main/java/com/swu/caresheep/data/model/Guardian.kt
  app/src/main/java/com/swu/caresheep/ui/elder/main/ElderActivity.kt
  app/src/main/java/com/swu/caresheep/ui/guardian/calendar/GuardianCalendarFragment.kt
  app/src/main/java/com/swu/caresheep/ui/start/SplashActivity.kt
  app/src/main/java/com/swu/caresheep/utils/CalendarUtil.kt
  app/src/main/java/com/swu/caresheep/utils/GoogleLoginClient.kt
Labels: refactor

#82 feat: 어르신 위치 추적 시, 포그라운드화 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/swu/caresheep/App.kt
  app/src/main/java/com/swu/caresheep/ElderMapsActivity.kt
  app/src/main/java/com/swu/caresheep/GuardianMapsActivity.kt
  app/src/main/java/com/swu/caresheep/ui/elder/main/ElderActivity.kt
  app/src/main/java/com/swu/caresheep/ui/guardian/GuardianActivity.kt
  app/src/main/java/com/swu/caresheep/utils/GpsForegroundService.kt
  app/src/main/java/com/swu/caresheep/utils/GpsNotificationManager.kt
  app/src/main/java/com/swu/caresheep/utils/LocationUtil.kt
  app/src/main/res/layout/activity_elder_maps.xml
  app/src/main/res/layout/activity_guardian_maps.xml
  app/src/main/res/values/strings.xml
Labels: feature

#89 fix: 보호자 지도에 인포창 추가
  app/src/main/java/com/swu/caresheep/ui/guardian/map/GuardianMapsActivity.kt
  app/src/main/res/drawable/shadow.xml
  app/src/main/res/drawable/shadow_custom_9patch.9.png
  app/src/main/res/layout/activity_guardian_maps.xml
  app/src/main/res/values/strings.xml
Labels: fix

#91 feat: 보호자 지도에 어르신 정보 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/swu/caresheep/ui/guardian/map/GuardianMapsActivity.kt
  app/src/main/res/drawable/shadow.xml
  app/src/main/res/layout/activity_guardian_add_schedule.xml
  app/src/main/res/layout/activity_guardian_connect.xml
  app/src/main/res/layout/activity_guardian_maps.xml
  app/src/main/res/layout/activity_guardian_schedule_detail.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/strings.xml
Labels: feature

#96 design : fcm 알림 유뮤 판단을 위한 이미지
  app/src/main/res/drawable/baseline_lens_24.xml
Labels: design

#97 design, feat : 보호자 화면에서 어르신 음성 녹음 관련 UI 작업
  app/src/main/java/com/swu/caresheep/elder/ElderVoiceSubActivity.kt
  app/src/main/java/com/swu/caresheep/recyclerview/RecordAdapter.kt
  app/src/main/java/com/swu/caresheep/recyclerview/RecycleMainRecordActivity.kt
  app/src/main/java/com/swu/caresheep/ui/guardian/GuardianVoiceDetailActivity.kt
  app/src/main/res/layout/activity_guardian_voice_detail.xml
  app/src/main/res/layout/activity_recycle_record_main.xml
  app/src/main/res/layout/layout_recycler_record_item.xml
Labels: feature, design
